### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by Ashpan** [abhishekmagdum/PersonalWebsite#1]
I'm unsure why, but you have you HTML, CSS, and JS files in the root directory. Thats fine until you look in the "personalwebsite" folder, you'll see files with the same name once again. You should fix that in your best interest.

**Comment by abhishekmagdum** [comment]
Yea, when making a new project with meteor, meteor decides to create its own folder even when you point it to the root of a directory. Due to this I had to move files from the folder meteor decided to create, to the root directory of the folder I chose to set to push. I still yet have to delete the folder meteor created.

**Comment by Ashpan** [comment]
Did you create your meteor project first or did you create your code first and then initialize a meteor project?

**Comment by abhishekmagdum** [comment]
I copied the files over. I still need to add the hidden meteor framework.
